name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install uv
          python -m pip install ruff

      - name: Run Ruff
        run: make lint
